### ISSUE TITLE
Error when running java

### ISSUE THREAD

**Issue by pertrai1** [adamtornhill/code-maat#1]
Hi, I am not well versed in java so bear with me. When I run this code from my repo directory, I get an error.

```
java -jar code-maat-0.5.1.jar -l logfile.log -c <vcs>
```

```
zsh: parse error near `\n'
```

Again, I am running this inside of my repository directory which I have a feeling I am doing wrong. Please let me know what it is that I need to do so that this will work. Thank you.

**Comment by adamtornhill** [comment]
There are two usage issues:
 1) You need to replace `<vcs>` with the name of one of the supported systems: `git`, `hg`, `svn`.
 2) If you build it from source you should run the standalone jar file.

Here's an example:
I've created a logfile for Code Maat itself and saved it to the file `maat_evo.log`. If I run the tool from inside the repository, my usage looks like this:

             adam$ java -jar target/code-maat-0.8.2-standalone.jar -l maat_evo.log -c git -a revisions

I'm running Java 7. Later versions work fine as well.

Please let me know if this solves your problem.

**Comment by pertrai1** [comment]
This did the trick. Thank you for the quick response and love the tool
