### ISSUE TITLE
P4 log parser error

### ISSUE THREAD

**Issue by eborgbjerg** [adamtornhill/code-maat#10]
I created a Perforce log file using the command given in the documentation.
It looks like the code-maat parser can't handle some lines I have, starting with 'Jobs fixed'.
The error from the parser says that it expected 'Affected' at that position.
Below is the log file content.

Change 401723 by ejbo@ejbo-home-fimbul on 2015/03/19 12:40:33
	FIM-29 ##scription here>
Jobs fixed ...
FIM-29 on 2015/03/19 by ejbo *closed*
	Fimbul unit test suite
Affected files ...
... //depot/fiks/fimbul/unittest/gmock-1.6.0/gtest/samples/test_fimbul_klip.cc#31 edit

Change 401722 by ejbo@ejbo-home-fimbul on 2015/03/19 10:21:54
	FIM-175 proxy ##on here>
Jobs fixed ...
FIM-40 on 2015/03/19 by ejbo *closed*
	Fjern hardkodet dato 01.01.2020 i army.cxx
Affected files ...
... //depot/fiks/fimbul/klip_syg.cxx#93 edit
... //depot/fiks/fimbul/klip_syg.hxx#16 edit

**Comment by eborgbjerg** [comment]
PS - after manual removal of the lines in question, analysis runs as expected.

**Comment by adamtornhill** [comment]
I've never worked with Perforce myself (that code is a contribution), but I'll have a look at it. From what I can see in the parser grammar, each message (e.g. "FIM-29 ...", "Jobs fixed...") should start with a tab. Is that the case in the example you pasted above too? And what lines did you have to remove to make it work?

**Comment by eborgbjerg** [comment]
Here is another snippet, in order to have a more clear example.
First line begins with 'Change' (then change-id, author etc.).
Next line starts with a tab and a comment follows. Here '<tab>Ups, ...'
3rd line is 'Jobs fixed...'
4th line has a socalled 'Job' identifier (here 'FIM-127') first, then some info about date + user + status. 5th line is a comment, and like the comment from line 2, it begins with a tab. In general, it seems that only comments start with a tab character.
I suspect that in general, there may be 0-N number of such Job sections in sequence, although my commits always are restricted to one.
Finally there is line 6: 'Affected files ...', and line 7 with a file affected.

So, to answer your questions:

In the example below, I remove lines 3,4 and 5, in order to get the analysis working.
Only comments seem to have a prepended tab character, as commented above.


Change 399449 by lpi001@lpi001-home-fimbul on 2015/02/17 13:26:45
	Ups, army bliver aldrig reduceret, har altid fuld g-dags antal
Jobs fixed ...
FIM-127 on 2015/03/02 by sysgen *closed*
	Ændringe i  belægningen af g-dage
Affected files ...
... //depot/fiks/fimbul/cerkl.cxx#100 edit

**Comment by eborgbjerg** [comment]
Ok, so the tab's are removed in the post - I have added <TAB> instead :)

Change 399449 by lpi001@lpi001-home-fimbul on 2015/02/17 13:26:45
<TAB>Ups, army bliver aldrig reduceret, har altid fuld g-dags antal
Jobs fixed ...
FIM-127 on 2015/03/02 by sysgen *closed*
<TAB>Ændringe i  belægningen af g-dage
Affected files ...
... //depot/fiks/fimbul/cerkl.cxx#100 edit

**Comment by eborgbjerg** [comment]
Ok, so 
Another attempt to persuade the post to indicate the tabs :):)

Change 399449 by lpi001@lpi001-home-fimbul on 2015/02/17 13:26:45
TAB!	Ups, army bliver aldrig reduceret, har altid fuld g-dags antal
Jobs fixed ...
FIM-127 on 2015/03/02 by sysgen *closed*
TAB!	Ændringe i  belægningen af g-dage
Affected files ...
... //depot/fiks/fimbul/cerkl.cxx#100 edit

**Comment by adamtornhill** [comment]
Thanks! I've pushed a fix for the bug. It works fine with the sample data you provided.
Please let me know if this solves your problem so that we can close this issue.

**Comment by eborgbjerg** [comment]
And thank you! I've tested with another (larger) sample file. Analysis runs, and the output looks correct at first inspection. I think you can close this issue. Thanks for working this out!

**Comment by LogicalChaos** [comment]
Thanks Adam for taking care of that!

**Comment by adamtornhill** [comment]
Ha ha - cool :) It was actually quite easy to fix. It was the rare kind of bug that you could solve by removing code. I like those.
