### ISSUE TITLE
Error on messages analysis regular expression

### ISSUE THREAD

**Issue by nascif** [adamtornhill/code-maat#12]
I am trying to use the new "messages" analysis but it doesn't seem to like the regular expression I am passing to it.
According to other tools it is a valid regex. Maybe Clojure uses a different syntax? 
I tried to find an example under the test directory but couldn't find any.

java -jar C:\Dropbox\bin\code-maat-0.9.0-SNAPSHOT-standalone.jar -l C:\temp\d4vanrx.txt -c git -a messages -e "(S[0-9]{,7})|[(]([A-Z]{1,}-[0-9]{1,})[)]|([A-Z]{1,}-[0-9]{1,})[:]" -o C:\temp\maat_output\messages.csv
Invalid argument:  Internal error - please report it. Details = Illegal repetition near index 6
(S[0-9]{,7})|[(]([A-Z]{1,}-[0-9]{1,})[)]|([A-Z]{1,}-[0-9]{1,})[:]

**Comment by nascif** [comment]
Here is a sample of the kind of commit messages I am trying to match against:

Merge remote-tracking branch 'origin/master'
(VAN-481) add parameter support to preview result
S1137461: moved methods from ReportBll ot VisualElementBll to remove dependency on VisualElementBll and help break circular dependencies
VAN-499: add parameter support to preview result

I want to capture VAN-481, VAN-499 and S1137461 from the data above.

PS: I created/validated the expression with Pythex (http://pythex.org/)

**Comment by adamtornhill** [comment]
There seems to be an unbalanced parenthesis in the the sample you pasted (I get that error from Pythex as well).
But I don't think that's the issue. It looks like the repetition operator needs a lower bound in Java. So instead of `{,7}`, try to specify `{1,7}`.
