### ISSUE TITLE
Components library

### ISSUE THREAD

**Issue by AndreaCrotti** [adamtornhill/code-maat#16]
Hi,
I wonder if you would be interested in implementing the components library:
https://github.com/stuartsierra/component/

It's a bit tricky to adapt it to an existing codebase but it can be done, and as the project becomes bigger could become a great advantage..
I

**Comment by adamtornhill** [comment]
Hi,

I'm not sure if components fit - code-maat doesn't maintain any state. Do you have some specific idea in mind?

One related thing I'd like to happen in the future is to introduce protocols for the parsers and analysers. Today they're just glued together by conventions.

**Comment by AndreaCrotti** [comment]
Yes well I don't think it's just about state, it can also decouple better the different components, but I don't have a specific idea in mind..
And if in the future this project will maintain some state (I don't know realtime graphs for example) it will become very handy.

Anyway I think protocols would be a better and easier thing to do at the moment..

**Comment by AndreaCrotti** [comment]
I'll close this since it's not a real issue, might create something later on for the protocols
