### ISSUE TITLE
git tags

### ISSUE THREAD

**Issue by AndreaCrotti** [adamtornhill/code-maat#17]
This is just a suggestion, but might be nice to tag the git revision whenever, which makes github understand your project history a bit better and is also easier to understand what is the last release.
It can still be done even now for previous versions potentially if you're interested in doing that, thanks

**Comment by adamtornhill** [comment]
Agree - it would be good to tag the history. I'll do that from now on.

If any one's interested in tagging historic releases, that would be great as well.

**Comment by AndreaCrotti** [comment]
Hi @adamtornhill I would like to do that but I don't think it's possible for me, since only people with write access to the repository can set tags..

http://stackoverflow.com/questions/12278660/adding-tags-to-a-pull-request

**Comment by AndreaCrotti** [comment]
Ok I'm going to close this since all is needed is just to add the tags from now on, and potentially add the previous ones, but only the repository owner can do this anyway..
thanks

**Comment by adamtornhill** [comment]
Hi @AndreaCrotti I finally got around to wrap-up a new release and this time I added a tag. Thanks for the suggestion on that!
