### ISSUE TITLE
NumberFormatException when trying to run Maat

### ISSUE THREAD

**Issue by hussein** [adamtornhill/code-maat#22]
Hi,

Thanks a lot for creating this awesome project. I'm trying it for our projects:

``` git log --all -M -C --numstat --date=short --pretty=format:'--%h--%ad--%an' --no-renames > log.log  ```

```java -jar target/code-maat-0.9.2-SNAPSHOT-standalone.jar -l log.log -c git -s summary```                                                                                             
>WARNING: update already refers to: #'clojure.core/update in namespace: incanter.core, being replaced by: #'incanter.core/update
The following errors occurred while parsing your command:
Error while parsing option "-s summary": java.lang.NumberFormatException: For input string: "summary"

Am I doing something wrong?

Btw, your presentation in EuroClojure was the best!

Thanks a lot.

**Comment by adamtornhill** [comment]
@hussein Thanks for your kind words! I hope you'll find the tool useful.

You're close: just replace `-s summary` with `-a summary`and it will work; All analyses are invoked with the `-a` switch.
