### ISSUE TITLE
Is it a valid logfile?

### ISSUE THREAD

**Issue by robertiansweetman** [adamtornhill/code-maat#25]
Hi Adam 

This is right at the edge of my technical envelope! =) Anyway, have a log file and am also pretty sure it's UTF-8 encoded. At least that's what it says when I open it in Notepad++ and Atom.

What other issues could be causing this error text? 

Invalid argument:  git2: Failed to parse the given file - is it a valid logfile?

Actually took the test simple_git2.txt file and tried to run it through this and it failed with the same error so I'm guessing this could be a case of user (has no clue) error :+1: 

Also - since I know NOTHING about clojure - is this warning relevant at all?? 
WARNING: update already refers to: #'clojure.core/update in namespace: incanter.core, being replaced by: #'incanter.core/update

Thanks!!

**Comment by adamtornhill** [comment]
Hi @robertiansweetman 

Could you please include a line that shows how you run code maat? What arguments do you use?

The warning is annoying, but not relevant. I'll try to get rid of it in a future version.

**Comment by robertiansweetman** [comment]
Hi @adamtornhill  

java -jar target/code-maat-0.9.2-SNAPSHOT-standalone.jar -l gitlog3.log -c git2 -a summary -o results.log 

Thanks :)

**Comment by adamtornhill** [comment]
Your command line arguments are fine, so I cannot tell what's wrong. Is it possible for you to send me a small part of your `gitlog3.log` that fails when you parse it? That would let us ensure that the format is correct.

**Comment by robertiansweetman** [comment]
Thanks - have pm'd you =)

**Comment by robertiansweetman** [comment]
@adamtornhill  - I've concluded (even with your excellent help) that my Java environment is deeply broken since I have zero expertise in this area. Making the mod you suggested to generate an error log didn't even work properly. I'll have to leave it at this point

**Comment by Kronnork** [comment]
@adamtornhill  Was this figured out? Since the issue still persists.

**Comment by adamtornhill** [comment]
@Kronnork The issue wasn't related to code maat, but to the environment. To get more specific help, you should open a new issue and share information on:
1. The versions of JDK and Git that you use,
2. A small sample log that fails to parse, and
3. Information on which shell you use.

Thanks!
