### ISSUE TITLE
Remove layer_mapper.clj?

### ISSUE THREAD

**Issue by chenrui333** [adamtornhill/code-maat#27]
I noticed that the two files are essentially the same, grouper.clj and layer_mapper.clj. So we should delete layer_mapper.clj (since the ns is grouper)

```
>diff code_maat/app/grouper.clj code_maat/app/layer_mapper.clj 
24c24
<     path      = #'^[\\w/\\\\\\.\\-]+'
---
>     path      = #'^[\\w/\\\\]+'
```

Thanks,
Rui

**Comment by adamtornhill** [comment]
Thanks a lot @chenrui333 for detecting this! Yes, the layer_mapper was essentially dead code left over from a refactoring. I've removed the module now.
