### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by RasmusWL** [adamtornhill/code-maat#32]
`http://www.adamtornhill.com/code/codemaat.htm` seems to be down currently

**Comment by adamtornhill** [comment]
I haven't noticed anything strange and the page works just fine now. What HTTP response do you get?

**Comment by RasmusWL** [comment]
working just fine now again, must just have been a small outage.

Saw your GOTO talk, great fun! Keep up the good work! :+1:

**Comment by adamtornhill** [comment]
Thanks a lot @RasmusWL for your kind words! I'm glad you liked my talk.
