### ISSUE TITLE
Support for Accurev

### ISSUE THREAD

**Issue by mikesmithson** [adamtornhill/code-maat#38]
Any chance that code-maat could support Accurev depots?

**Comment by adamtornhill** [comment]
I've never worked with AccuRev, but from what I've read about it, yes, code-maat could be extended to support AccuRev. You should be able to extract enough data through the `hist` command and extend code-maat with a new parser to transform that data to the code-maat internal format. However, I don't think you're able to get code churn metrics out of AccuRev that way, but I could be wrong.
