### ISSUE TITLE
code maat Parse error at line 1 on code maat sources

### ISSUE THREAD

**Issue by tomer-ben-david** [adamtornhill/code-maat#40]
Hi, I did git clone for code maat then:

```
code-maat$ git log --all --numstat --date=short --pretty=format:'--%h--%ad--%aN' --no-renames > git.log
java -jar target/code-maat-1.0-SNAPSHOT-standalone.jar -l git.log -c git
```

and result:

```
Invalid argument:  java.lang.IllegalArgumentException: input: --788a0f3--2016-07-19--Adam Tornhill
1	1	README.md
, reason: Parse error at line 1, column 1:
--788a0f3--2016-07-19--Adam Tornhill
^
Expected:
[

This is Code Maat, a program used to collect statistics from a VCS.
Version: 1.0-SNAPSHOT
```

can you help please?

**Comment by adamtornhill** [comment]
@tomer-ben-david Sure, you just need to specify a different option: replace `-c git` with `-c git2`.

code-maat supports two different Git log formats and the command line argument has to match the format of the log as documented [here](https://github.com/adamtornhill/code-maat#generate-a-git-log-file-using-the-following-command).

**Comment by tomer-ben-david** [comment]
excellent!! missed that, its working.

**Comment by adamtornhill** [comment]
Perfect - happy to hear that! You may also want to have a look at [https://codescene.io/](https://codescene.io/), which automates all these steps and visualizations. It's a free service for open source.

**Comment by tomer-ben-david** [comment]
thanks, do you still have: 'merge_comp_freqs.py'?

**Comment by tomer-ben-david** [comment]
please ignore found it here: https://github.com/adamtornhill/maat-scripts
