### ISSUE TITLE
Grouping causes incorrect CSV output

### ISSUE THREAD

**Issue by vchircu** [adamtornhill/code-maat#43]
Hi,

I am following the code samples from the book and the grouping commands output incorrect text.

For example:

1. maat -l maat_evo.log -c git -a coupling -g maat_src_test_boundaries.txt
entity,coupled,degree,average-revs
",80,65est
2.  maat -l maat_evo.log -c git -a coupling -g maat_src_detailed_test_boundaries.txt
entity,coupled,degree,average-revs
",42,50to end Tests
",42,49is Test
",Parsers Test,41,49

I have tried both the latest version and 0.8.5 and I get the same results. I am running on Windows 8.

Thanks!

**Comment by adamtornhill** [comment]
@vchircu I just tried the command with the latest version of code maat and it works just fine. My `maat_src_test_boundaries.txt` groups look like:

```
src/code_maat => Code
test/code_maat => Test
```
I get the following output:
````
entity,coupled,degree,average-revs
Code,Test,80,65
````
I suspect that it's some encoding issue. Could you please check the encoding of the input files (code maat supports a custom encoding too)? What shell do you use to run the commands?

**Comment by vchircu** [comment]
@adamtornhill, the encoding of the input file is UTF-8. I've used cmder, running cmd or powershell, and I've got the same result. 

I noticed that if I write the output to a file, it looks differently (and I can extract the required data from it). 

Example:

1. `maat -l maat_evo.log -c git -a coupling -g maat_src_test_boundaries.txt > test.csv`
entity,coupled,degree,average-revs
"Code
",Test,80,655
2. `maat -l maat_evo.log -c git -a coupling -g maat_src_detailed_test_boundaries.txt > test.csv`
entity,coupled,degree,average-revs
"Code
","End to end Tests
",42,50
"Analysis Test
","Code
",42,49
"Code
",Parsers Test,41,49

Some of the entities are surrounded by " and there seems to be an extra space and a line break.

**Comment by adamtornhill** [comment]
@vchircu Have you tried to run it in a Git BASH shell? If you want, please send me the result file and I'll have a look at it to see if I can spot the problem.

**Comment by vchircu** [comment]
@adamtornhill I tried running the commands in Git BASH and I get the same result. Here is a result file:

[coupling.txt](https://github.com/adamtornhill/code-maat/files/722725/coupling.txt)

Thanks.

**Comment by adamtornhill** [comment]
Thanks @vchircu , but I'd need you to pipe the result to a file and share that file with me:
```
maat -l maat_evo.log -c git -a coupling -g maat_src_test_boundaries.txt > test.csv
```
I suspect an encoding issue so I'd like to look at the result file as created in your environment.

**Comment by vchircu** [comment]
@adamtornhill, that's what I did. The coupling.txt file was obtained with the following command:
`maat -l maat_evo.log -c git -a coupling -g maat_src_detailed_test_boundaries.txt > coupling.txt`

**Comment by adamtornhill** [comment]
Sorry, but that's not what I see as I download `coupling.txt`:

```
E:\Learning\YCAACS\code-maat>REM @echo off 

E:\Learning\YCAACS\code-maat>java -jar E:\Learning\YCAACS\winmaat0.8.5\code-maat-1.0-SNAPSHOT-standalone.jar -l maat_evo.log -c git -a coupling -g maat_src_detailed_test_boundaries.txt 
entity,coupled,degree,average-revs
"Code
","End to end Tests
",42,50
"Analysis Test
","Code
",42,49
"Code
",Parsers Test,41,49
```
It looks like it has captured your whole session.

**Comment by vchircu** [comment]
That's how all files are generated when I pipe the output of code maat to a file. I use another script to remove the first 4 lines from it.

**Comment by adamtornhill** [comment]
Have you tried to let code maat write the results to file? You do that with the `--outfile` option, like `--outfile coupling.csv` instead of piping in the prompt.

**Comment by vchircu** [comment]
I didn't tried this before. With this approach, it removed the extra lines, but there still are extra line breaks. It produced the following file:
[coupling.txt](https://github.com/adamtornhill/code-maat/files/723418/coupling.txt)

**Comment by adamtornhill** [comment]
I'm trying to track this down since I cannot reproduce it myself. Is it just the `-g` option that gives you odd output? Does it work as expected when you run a normal, file-level analysis?

**Comment by vchircu** [comment]
Yes, only the `-g` option gives odd output. I've ran all the other commands in the book and they all worked as expected.

**Comment by adamtornhill** [comment]
I had a new look at the source code for the grouping feature and unfortunately I couldn't find any explanation for the problem. As a last resort, could you please share your `maat_src_detailed_test_boundaries.txt` file?

**Comment by vchircu** [comment]
Sure. Here is the file:
[maat_src_detailed_test_boundaries.txt](https://github.com/adamtornhill/code-maat/files/731758/maat_src_detailed_test_boundaries.txt)

Thanks, @adamtornhill

**Comment by adamtornhill** [comment]
Alright - I finally found the problem. Your file with the grouping uses `^M` characters (CRs) to terminate each line. I just converted those CR:s to new lines (`\n`) and everything worked fine.

This is something I'd like to fix in Code Maat so that it tolerates both formats.

**Comment by vchircu** [comment]
Ok, makes sense. Thanks for looking into this!
