### ISSUE TITLE
Churn gives wrong output

### ISSUE THREAD

**Issue by rquinlivan** [adamtornhill/code-maat#44]
What does the "commits" column on the churn output represent? If it is meant to represent the total number of commits for the file, then it's reporting incorrectly.

**Comment by adamtornhill** [comment]
The meaning of the commits column depends on what kind of churn analysis you run and the scope of that analysis. In the `abs-churn` analysis it represents the number of commits per day. In `entity-churn` the number of commits match what you get from the `revisions` analysis. Which analysis do you refer to?

**Comment by adamtornhill** [comment]
No response - closing the issue. I'll re-open it if needed.
