### ISSUE TITLE
Can I get the record of code change by code-maat?

### ISSUE THREAD

**Issue by lanyuesl** [adamtornhill/code-maat#46]
Hi, 
Here is an engineer from **Huawei Technologies Co.,Ltd..** We are working on a topic ***How to get the record of code change by VCS?***
We want to know which lines of code were changed by who and at when through analyzing the log of VCS by some tools. Code-maat seems to be what we are looking for.

**Comment by adamtornhill** [comment]
Hi @lanyuesl 

There are several options here. Do you think you could describe your requirements in a bit more detail? That way I could give you better advices.

For example, a plain `git blame` gives you these details per file. Code Maat accumulates the contributions over time. In addition, we have [codescene.io](https://codescene.io/) that automates these analyses.

**Comment by lanyuesl** [comment]
Can you join my gitter chat-room so that we can talk in ditail？
I can not talk too much in public.
Thanks.

**Comment by lanyuesl** [comment]
Or connect me by my public email: *github.public.222@gmail.com*.
Thank you

**Comment by adamtornhill** [comment]
Closing - moved to private correspondence.
