### ISSUE TITLE
Please publish code-maat on clojars or maven central

### ISSUE THREAD

**Issue by jimbethancourt** [adamtornhill/code-maat#50]
It would be wonderful if code-maat could be published on http://www.clojars.org or http://central.maven.org  This would allow folks to leverage code-maat as a library and call its APIs.

Thanks,
Jim

**Comment by adamtornhill** [comment]
Sure, it is a good idea and I want to do it. I'll see if I get a bit of spare time over the next days.

**Comment by jimbethancourt** [comment]
Thanks Adam!  I love what you've done :-)  Keep up the great work!

**Comment by adamtornhill** [comment]
@jimbethancourt Thanks for your kind words -- I'm glad you like it.

The code-maat JAR is now available at https://clojars.org/code-maat
