### ISSUE TITLE
coupling analisis is not working

### ISSUE THREAD

**Issue by mauro2357** [adamtornhill/code-maat#52]
When i run the command java -jar code-maat.jar -l “[maatfreqs.csv](https://github.com/adamtornhill/code-maat/files/1600515/maatfreqs.-.copia.txt)" -c git -a coupling, the program doesn´t show information.
![image](https://user-images.githubusercontent.com/7376390/34522993-81c2bc76-f063-11e7-8732-eac2a9cd4d7c.png)

**Comment by adamtornhill** [comment]
This may be because there aren't any strong temporal dependencies. You could try to decrease the  `--min-coupling` option and increase the `--max-changeset-size` option.
