### ISSUE TITLE
csv_as_enclosure_json.py is not calculating weight

### ISSUE THREAD

**Issue by mauro2357** [adamtornhill/code-maat#53]
I am running the python script csv_as_enclosure_json.py and the json is always generated with 0 in the weight attribute.

In debug mode the function normalized_weight_for is not executing "if module_name in normalized_weights:"

These are my files

[countlines-domina04012018.txt](https://github.com/adamtornhill/code-maat/files/1605003/countlines-domina04012018.txt)
[revisions-domina04012018.txt](https://github.com/adamtornhill/code-maat/files/1605004/revisions-domina04012018.txt)

And this is the way i execute the script

python csv_as_enclosure_json.py
 --structure "countlines-domina04012018.csv" --weights "revisions-domina04012018.csv" - weightcolumn 2 > jsond3Domina.json

**Comment by adamtornhill** [comment]
This script is not part of code-maat. Is it the one that was referenced in my book? In that case, please check the recent revision of the script here: https://github.com/adamtornhill/maat-scripts

You should leave out the `weightcolumn` argument when invoking the script. We should also move the discussion to the `maat-scripts` repository if you have any follow up questions on the scripts.

**Comment by adamtornhill** [comment]
The discussion was moved to the above referenced issue in another repo.
