### ISSUE TITLE
Logical Coupling - Mining

### ISSUE THREAD

**Issue by wogscpar** [adamtornhill/code-maat#55]
Hello,

I've been using the code-maat tool to mine features from a git repository, especially the logic coupling. What I'm facing is the scenario that I want to mine the coupling changes over a time. So what I'm wondering is if it's possible to get all couplings by just running on the latest revision? Or do I need to do as I'm doing now and run the tool on each revision and then track the coupling changes myself?

Best regards,

Oscar

**Comment by adamtornhill** [comment]
Hi @wogscpar 

You could generate several Git logs using the `--before` and `--after` options to specify a date interval of interest. Then you run code-maat on each of those log files, which should allow you to detect trends.

Does this answer your question?

**Comment by wogscpar** [comment]
Hello @adamtornhill,

Almost. That's how I'm doing it today. The question is more if code-maat is executed on the latest revision, would it be possible for it to output the same result as if it would be executed on each individual log?

**Comment by adamtornhill** [comment]
Yes, it would be possible to implement such trends, but the support isn't there today. For example, code-maat could be expanded to take `--before`and `--after` arguments too, and use them to do the filtering of a full log based on the latest revision. That would save the roundtrip to `git` for each log.
