### ISSUE TITLE
messages: unable to run code maat with -a messages

### ISSUE THREAD

**Issue by jbiswas** [adamtornhill/code-maat#57]
Do you have an example of how to analyze commit messages?

I tried ```-a messages -e fix``` but I get no results.

**Comment by jbiswas** [comment]
Thanks Adam. Actually what I was looking for was how often a file is involved in bug fixes. I ended up using a long-ish bash command to get that result.

**Comment by adamtornhill** [comment]
Solved and addressed in issue #74
