### ISSUE TITLE
Exclusion of folder inside Repository

### ISSUE THREAD

**Issue by velanbabu** [adamtornhill/code-maat#60]
how to exclude certain folders inside repository during generation of the log?

**Comment by adamtornhill** [comment]
In case of Git, it uses pathspecs to limit paths on the command line. To give you an example, let's say I want to exclude everything in my `vendor/` folder. I would then use the following pattern: 

`git log --numstat -- . ":(exclude)vendor/*"`

Note that you would need to add the other options required by Code Maat too. Other version-control systems might have a similar concept, but I'm less familiar with them.

Does this help?

**Comment by velanbabu** [comment]
Great. Its work. This might be useful for others. If we want to exclude more than a folder below syntax
git log --numstat -- . ":(exclude)vendor/*" ":(exclude)test/*" > output.log
