### ISSUE TITLE
File formats under Windows

### ISSUE THREAD

**Issue by duncanmccreadie** [adamtornhill/code-maat#62]
I am running the Docker Container version of Code Maat and can see it is trying to work but it seems unable to cope with the Git log I have generated using the command you suggest in the documentation. I have tried saving it in various different encodings to see if that fixed the issue but it doesn't. Any other ideas on what might be going wrong?

I am running Docker for Windows for clarity.

[codemaat2.log](https://github.com/adamtornhill/code-maat/files/3176261/codemaat2.log)

**Comment by adamtornhill** [comment]
Have you tried to specify the encoding using the `-input-encoding` option when running Code Maat?

**Comment by duncanmccreadie** [comment]
Worked it out in the end by running the container with a extra-point of
bash. It became apparent that it couldn't see the mounted drive due to the
encryption program running on my data drive. Once that was obvious , a
change of directory and all is well. Perhaps the error message could be
better in this regard?

Anyway thanks for replying. I am working through your excellent book now.
