### ISSUE TITLE
Issues while running code maat

### ISSUE THREAD

**Issue by psrijay** [adamtornhill/code-maat#68]
Hey adam ,
I not able to generate log file with this command 
git log --all --numstat --date=short --pretty=format:'--%h--%ad--%aN' --no-renames --after=2016-10-01
I am running it in a cloned project for which numstat is getting displayed but log isn't getting generated
can you just guide me how to run code-maat for a git project 
I have lein install already using package manager on ubuntu 18.04
Do i need to create a a clj file for my git project or shall i include it in a lein app.

**Comment by adamtornhill** [comment]
Hi @psrijay 

The `git log` command isn't related to Code Maat. The `git log` command itself doesn't generate a file, so to persist it you need to pipe it (e.g. `> mylog.txt`) to a file.
