### ISSUE TITLE
[question] Example GROUP file for the --group command line option

### ISSUE THREAD

**Issue by hydrosquall** [adamtornhill/code-maat#71]
Hi Adam,

Thanks for making this powerful tool free and open source!

I was wondering if you could provide an example GROUP file for usage with the `-g` CLI option for grouping related entities. I have some files  I found the test file that implements this functionality which might offer some clues, but I'm not familiar enough with Clojure to determine how to write my input text files. I have some deep folders that I'd like to roll-up into a single entity to reduce the noisiness of the visualization.

https://github.com/adamtornhill/code-maat/blob/master/test/code_maat/app/grouper_test.clj

Thanks for any pointers or ideas!

**Comment by hydrosquall** [comment]
I read through the grouper class source, and using these lines:

https://github.com/adamtornhill/code-maat/blob/ebd2b757ae31510b5cf52d0e11fafa82a7e062d1/src/code_maat/app/grouper.clj#L17-L20

figured out how to write a custom grouping file for my project. It was along the lines of

```
src/components/utils => utils
src/pages/PageB => PageB
src/pages/PageA/*.test.js => PageATests
#...etc
```

**Comment by adamtornhill** [comment]
Thanks for your kind words! I'm happy to hear that.

There are some sample text files in the `end_to_end` test folder, for example [this one](https://github.com/adamtornhill/code-maat/blob/ebd2b757ae31510b5cf52d0e11fafa82a7e062d1/test/code_maat/end_to_end/regex-and-text-layers-definition.txt)

Here's an excerpt:

```
src/Features/Core      => Core
^src\/.*\/.*Tests\.cs$ => CS Tests
```

The format is `regex_pattern => logical_group_name`. Code Maat takes everything that matches a regex and analyses it as a holistic whole by aggregating all file contributions for the matches.

I'll try to make a PR soon that adds an example to the docs. It's a good idea.
