### ISSUE TITLE
Parse error at line 1, column 1

### ISSUE THREAD

**Issue by joannegs** [adamtornhill/code-maat#76]
Hey, 

trying to use Code Maat I've been facing the following errors, even after using the formats recommended on the documentation and it's correspondenting -c flags. 

![image](https://user-images.githubusercontent.com/36765523/137978840-1325aed3-34cf-47d3-bc51-a4723af27ca2.png)

![image](https://user-images.githubusercontent.com/36765523/137979532-8a5e5690-af73-4a7c-aad1-bfb7b4de5cd1.png)

I tried to extract the log file as a .log and as a .txt and both extensions won't work for me. 

I was thinking maybe I could get some help?

**Comment by adamtornhill** [comment]
Hi @joannegs 

Could you share the full command you are using as well as a small snippet of the Git log? I could then take a look at it.

**Comment by joannegs** [comment]
Sure, 

I'm using the commands: 

> git log --all --numstat --date=short --pretty=format:'--%h--%ad--%aN' --no-renames --before=2019-01-01 > loggit.log 

> java -jar code-maat-1.0-standalone.jar -l loggit.log -c git2 -a coupling -o resultado.cvs

And that's the log file I'm passing to the tool:

![log_snippet](https://user-images.githubusercontent.com/36765523/138388984-4a9d1706-8b23-465c-a9d1-d1aa57179c15.png)

**Comment by mdclement** [comment]
I'm seeing the same thing using the jar

![image](https://user-images.githubusercontent.com/1100612/145094084-bd21da51-dbef-4532-8c02-c024286fc614.png)

`git log --all --numstat --date=short --pretty=format:'--%h--%ad--%aN' --no-renames --after=2020-06-01 > logfile.log`

`java -jar code-maat-1.0.2-standalone.jar -l logfile.log -c git2`

The beginning of my gitlog looks like:

`--f2e52a42e--2021-12-07--Bharat
--fa03a07a5--2021-12-07--Billy
--7089a0bea--2021-12-07--Rehman Gull
3	0	AfterSchool/Areas/Org/Controllers/ActivityController.cs
1	1	AfterSchool/Areas/Org/Views/Activity/Index.cshtml`

**Comment by adamtornhill** [comment]
@mdclement I took a look, and your example parses without problems. I ran it via the unit tests.

I suspect that this could be a text encoding issue. Could you please look at the encoding of your Git log file?

**Comment by ajdelcimmuto** [comment]
I had a similar issue, but then ran the same commands  in a git bahs shell and my issue was solved.

**Comment by adamtornhill** [comment]
@ajdelcimmuto Thanks for pointing that out! It's the preferred solution. I should have known: I actually included the following recommendation in Your Code as a Crime Scene:

![image](https://user-images.githubusercontent.com/5179769/152151145-94cfeeda-d38f-4d9b-b6bd-0d90d0c4ca55.png)
