### ISSUE TITLE
How is files deletion detected?

### ISSUE THREAD

**Issue by amaslenn** [adamtornhill/code-maat#77]
According to the recommended `git log` command, `code-maat` consumes only number of changes and ignores if a file was deleted. It leads to deleted files appear in "long-no-change" list.

@adamtornhill could you please elaborate on how it is analyzed?

**Comment by adamtornhill** [comment]
@amaslenn Yes, that's correct: deleted files are included in the version-control log too, meaning they will get analysed.
I used to resolve this by filtering the code maat output based on `git ls-files`.

One limitation in code maat is that it doesn't track renamed and moved content. As such, renamed files look like a deletion + addition of a new file. We implemented full rename tracking in CodeScene if that's an option for you.
