### ISSUE TITLE
Does it allow 'from' date and/or 'to' date to specified? i.e to retrieve data between a specific timeline

### ISSUE THREAD

**Issue by ErnestFistozz** [adamtornhill/code-maat#79]
Hi, 

Great tool. I have a specific use case i would like to know if the tool caters for. 
Is it possible to specify 'from' and 'to' dates, so say I want to gather the stats from X day to Y day.. eg from 2020-01-01 to 2021-12-01.. Another tool i came across used the 'before' , is there something similar with this tool?

how to would i collect such information.

**Comment by adamtornhill** [comment]
Hi @ErnestFistozz 

Yes, you can control those parameters when you generate the Git log that code maat uses as input. Just specify the `--after` and `--before` flags for filtering commits by date when generating the log file.
